Partial Public Class IRCConnection
    Event AwayCancelled(ByVal sender As IRCConnection, ByVal Message As String)
    Event AwaySet(ByVal sender As IRCConnection, ByVal Message As String)
    Event BanList(ByVal sender As IRCConnection, ByVal Channel As String, ByVal BannedUser As String, ByVal BanningUser As String, ByVal Time As Date)
    Event BanListEnd(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event NicknameChange(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal NewNick As String)
    Event NicknameChangeSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal NewNick As String)
    Event ChannelAction(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Action As String)
    Event ChannelActionHighlight(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Action As String)
    Event ChannelAdmin(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelAdminSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelBan(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelBanSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelTimestamp(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Timestamp As Date)
    Event ChannelCTCP(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Message As String)
    Event ChannelDeAdmin(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeAdminSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeHalfOp(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeHalfOpSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeHalfVoice(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeHalfVoiceSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeOp(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeOpSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeOwner(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeOwnerSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeVoice(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelDeVoiceSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelExempt(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelExemptSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelHalfOp(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelHalfOpSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelHalfVoice(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelHalfVoiceSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelInviteExempt(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelInviteExemptSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelJoin(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String)
    Event ChannelJoinSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String)
    Event ChannelJoinDeniedBanned(ByVal sender As IRCConnection, ByVal Channel As String)
    Event ChannelJoinDeniedFull(ByVal sender As IRCConnection, ByVal Channel As String)
    Event ChannelJoinDeniedInvite(ByVal sender As IRCConnection, ByVal Channel As String)
    Event ChannelJoinDeniedKey(ByVal sender As IRCConnection, ByVal Channel As String)
    Event ChannelKick(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal Reason As String)
    Event ChannelKickSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal Reason As String)
    Event ChannelList(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Users As Integer, ByVal Topic As String)
    Event ChannelMessage(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Message As String)
    Event ChannelMessageSendDenied(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event ChannelMessageHighlight(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Message As String)
    Event ChannelMode(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Channel As String, ByVal Direction As Boolean, ByVal Mode As String)
    Event ChannelModeSelf(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Channel As String, ByVal Direction As Boolean, ByVal Mode As String)
    Event ChannelModeUnhandled(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Channel As String, ByVal Direction As Boolean, ByVal Mode As String)
    Event ChannelModesSet(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Channel As String, ByVal Modes As String)
    Event ChannelModesGet(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Modes As String)
    Event ChannelNotice(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Message As String)
    Event ChannelOp(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelOpSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelOwner(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelOwnerSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelPart(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Reason As String)
    Event ChannelPartSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Reason As String)
    Event ChannelQuiet(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelQuietSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelRemoveExempt(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelRemoveExemptSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelRemoveInviteExempt(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelRemoveInviteExemptSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelRemoveKey(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String)
    Event ChannelRemoveLimit(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String)
    Event ChannelSetKey(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Key As String)
    Event ChannelSetLimit(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Limit As Integer)
    Event ChannelTopic(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Topic As String)
    Event ChannelTopicChange(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal NewTopic As String)
    Event ChannelTopicStamp(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Setter As String, ByVal SetDate As Date)
    Event ChannelUsers(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Names As String)
    Event ChannelUnBan(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelUnBanSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelUnQuiet(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelUnQuietSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String, ByVal MatchedUsers As String())
    Event ChannelVoice(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event ChannelVoiceSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String, ByVal Target As String)
    Event Connected(ByVal sender As IRCConnection)
    Event Connecting(ByVal sender As IRCConnection, ByVal Host As String, ByVal Endpoint As System.Net.IPEndPoint)
    Event ConnectingFailed(ByVal sender As IRCConnection, ByVal Exception As Exception)
    Event PrivateCTCP(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Message As String)
    Event SendCTCP(ByVal sender As IRCConnection, ByVal Target As IRCUser, ByVal Message As String)
    Event SendDCCChatOffer(ByVal sender As IRCConnection, ByVal Target As String)
    Event SendDCCOffer(ByVal sender As IRCConnection, ByVal Target As IRCUser, ByVal Message As String)
    Event SendMessage(ByVal sender As IRCConnection, ByVal Target As String, ByVal Message As String)
    Event DCCChatOffer(ByVal sender As IRCConnection, ByVal Sender As IRCUser)
    Event DCCChatAlreadyOffering(ByVal sender As IRCConnection, ByVal Target As IRCUser)
    Event DCCOffer(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Message As String)
    Event DCCBadOffer(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Message As String)
    Event DCCFileResumeRequest(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Filename As String, ByVal Position As Object)
    Event DCCFileSendOffer(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Filename As String, ByVal Length As Long)
    Event Disconnected(ByVal sender As IRCConnection, ByVal ErrorMessage As String)
    Event WaitingToReconnect(ByVal sender As IRCConnection, ByVal Interval As Decimal, ByVal Attempts As Integer, ByVal MaxAttempts As Integer)
    Event Exception(ByVal sender As IRCConnection, ByVal Exception As Exception)
    Event ExemptList(ByVal sender As IRCConnection, ByVal Channel As String, ByVal ExemptedUser As String, ByVal ExemptingUser As String, ByVal Time As Date)
    Event ExemptListEnd(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event Invite(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Channel As String)
    Event InviteSent(ByVal sender As IRCConnection, ByVal Target As String, ByVal Channel As String)
    Event InviteList(ByVal sender As IRCConnection, ByVal Channel As String, ByVal InvitedUser As String, ByVal InvitingUser As String, ByVal Time As Date)
    Event InviteListEnd(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event InviteExemptList(ByVal sender As IRCConnection, ByVal Channel As String, ByVal ExemptedUser As String, ByVal ExemptingUser As String, ByVal Time As Date)
    Event InviteExemptListEnd(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event Killed(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Reason As String)
    Event LookingUpHost(ByVal sender As IRCConnection, ByVal Hostname As String)
    Event LookingUpHostFailed(ByVal sender As IRCConnection, ByVal Hostname As String, ByVal ErrorMessage As String)
    Event MOTD(ByVal sender As IRCConnection, ByVal Message As String)
    Event MOTDSkipped(ByVal sender As IRCConnection)
    Event Names(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event NamesEnd(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Message As String)
    Event NicknameInvalid(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event NicknameTaken(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event NicknameChangeFailed(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event PrivateNotice(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Message As String)
    Event SendNotice(ByVal sender As IRCConnection, ByVal Target As String, ByVal Message As String)
    Event Ping(ByVal sender As IRCConnection, ByVal ServerName As String)
    Event PingReply(ByVal sender As IRCConnection, ByVal Sender As String)
    Event PrivateMessage(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Message As String)
    Event PrivateAction(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Action As String)
    Event Quit(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Reason As String)
    Event QuitSelf(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Reason As String)
    Event RawLineReceived(ByVal sender As IRCConnection, ByVal Message As String)
    Event RawLineReceivedUnhandled(ByVal sender As IRCConnection, ByVal Message As String)
    Event RawLineSent(ByVal sender As IRCConnection, ByVal Message As String)
    Event UserModesSet(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Modes As String)
    Event Wallops(ByVal sender As IRCConnection, ByVal Sender As IRCUser, ByVal Message As String)
    Event ServerNotice(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Message As String)
    Event ServerError(ByVal sender As IRCConnection, ByVal Message As String)
    Event ServerMessage(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Numeric As String, ByVal Message As String)
    Event ServerMessageUnhandled(ByVal sender As IRCConnection, ByVal Sender As String, ByVal Numeric As String, ByVal Message As String)
    Event TimeOut(sender As IRCConnection)
    Event WhoList(ByVal sender As IRCConnection, ByVal Channel As String, ByVal Username As String, ByVal Address As String, ByVal Server As String, ByVal Nickname As String, ByVal Flags As String, ByVal Hops As Integer, ByVal FullName As String)
    Event WhoIsAuthenticationLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String, ByVal Account As String)
    Event WhoIsAwayLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal AwayReason As String)
    Event WhoIsChannelLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Channels As String)
    Event WhoIsEnd(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event WhoIsIdentified(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event WhoIsIdleLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal IdleTime As TimeSpan, ByVal SignOnTime As Date, ByVal Message As String)
    Event WhoIsNameLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Username As String, ByVal Host As String, ByVal FullName As String)
    Event WhoIsOperLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event WhoIsHelperLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
    Event WhoIsRealHostLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String, ByVal RealUsername As String, ByVal RealHost As String, ByVal RealIP As String)
    Event WhoIsServerLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Server As String, ByVal Info As String)
    Event WhoIsSpecialLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Numeric As String, ByVal Message As String)
    Event WhoWasNameLine(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Username As String, ByVal Host As String, ByVal FullName As String)
    Event WhoWasEnd(ByVal sender As IRCConnection, ByVal Nickname As String, ByVal Message As String)
End Class